"""Minimal PDF text extraction, for asserting what the notice actually says.

Why this exists rather than a dependency: no PDF library is installed, and adding one to
`requirements.txt` for tests alone is weight the deployed service would carry for nothing.
The notice is generated by ReportLab, so the input is narrow and predictable — Flate-encoded
content streams with text drawn by `Tj`/`TJ` — and a hundred lines of parsing covers it.

This is emphatically not a general PDF parser. It exists so tests can assert that a legal
notice contains the citation and the offending value, instead of only asserting the bytes
begin with `%PDF-`. A notice that renders but cites nothing is the failure that matters.
"""

from __future__ import annotations

import re
import zlib

_STREAM = re.compile(rb"stream\r?\n(.*?)\r?\nendstream", re.DOTALL)
# A PDF string literal: parens, with backslash escapes permitted inside.
_LITERAL = re.compile(rb"\((?:[^()\\]|\\.)*\)", re.DOTALL)
_ESCAPE = re.compile(rb"\\([()\\])")


def _decode_literal(literal: bytes) -> str:
    """Strip the delimiting parens and unescape. ReportLab emits Latin-1 for base-14 fonts."""
    return _ESCAPE.sub(rb"\1", literal[1:-1]).decode("latin-1", errors="replace")


def extract_text(pdf: bytes) -> str:
    """Return all text drawn in the document, whitespace-normalised.

    Word order follows the content stream, which for our generated notice is reading order.
    Inter-word spacing is not reconstructed from text positioning, so callers should assert
    on words and short phrases rather than exact sentences.
    """
    pieces: list[str] = []

    for match in _STREAM.finditer(pdf):
        try:
            content = zlib.decompress(match.group(1))
        except zlib.error:
            continue  # an image XObject or an uncompressed stream; no text to read
        for literal in _LITERAL.finditer(content):
            pieces.append(_decode_literal(literal.group(0)))

    return re.sub(r"\s+", " ", " ".join(pieces)).strip()
